# Generated by Django 5.0.1 on 2024-01-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('addr', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('features', models.TextField()),
            ],
        ),
    ]
