# Generated by Django 5.0.1 on 2024-01-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='shelterapp/static/images')),
                ('addr', models.TextField()),
                ('docu', models.FileField(upload_to='shelterapp/static/images')),
            ],
        ),
    ]
