# Generated by Django 5.0.1 on 2024-01-14 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='static/images')),
                ('type', models.CharField(choices=[('1BHK', '1 Bedroom, Hall, Kitchen'), ('2BHK', '2 Bedrooms, Hall, Kitchen'), ('3BHK', '3 Bedrooms, Hall, Kitchen'), ('4BHK', '4 Bedrooms, Hall, Kitchen')], max_length=10)),
                ('rent', models.IntegerField()),
                ('Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='shelterapp.property')),
            ],
        ),
    ]
