# Generated by Django 5.0.1 on 2024-01-15 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0002_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='tenant_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('rent_date', models.IntegerField()),
                ('Tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterapp.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterapp.unit')),
            ],
        ),
    ]
