# Generated by Django 5.0.1 on 2024-01-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0003_alter_unit_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='Property',
            field=models.CharField(max_length=50),
        ),
    ]
