# Generated by Django 5.0.1 on 2024-01-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0004_alter_unit_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='img',
            field=models.FileField(upload_to='shelterapp/static/images'),
        ),
    ]
