# Generated by Django 5.0.1 on 2024-01-14 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0005_alter_unit_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='Property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='shelterapp.property'),
        ),
    ]
